version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345678

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
