# Generated by Django 4.2 on 2023-04-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todomainapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
